
sudo: false
language: C
compiler:
  - gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-6
      -g++-6
install:
- "[ $CXX = g++ ] && export CXX=g++-6 || true"
script:
- cd software/tests/fixed
- make test
