language: c
sudo: true

before_install:
 - sudo apt-get update -qq

script:
 - gcc -o tools/sim/hf_riscv_sim/hf_riscv_sim.c tools/sim/hf_riscv_sim/hf_riscv_sim
 - tools/sim/hf_riscv_sim/hf_riscv_sim
 - cd /hf-risc-st/software/tests/fixed
 - make test


after_script:
 - pwd
 - ls

after_success:
 - echo "Success"

after_failure:
 - echo "Fail"
